name: laravel
recipe: laravel

config:
  php: '7.3'
  webroot: public
  xdebug: false
  via: nginx:1.18
  database: mariadb:10.4
  cache: redis:5

services:
  pma:
    type: phpmyadmin:5.0
    overrides:
      environment:
        PMA_HOST: database
  node:
    type: node
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php:7.3
    scanner: false
    overrides:
      ports:
        - '22'
    build_as_root:
      - mkdir /run/sshd
      - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      - echo root:password | chpasswd
      - service ssh reload
    run_as_root:
      - service ssh start

tooling:
  npm:
    service: node
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  redis-cli:
    service: cache

proxy:
  pma:
    - pma-laravel.lndo.site
  mailhog:
    - mailhog-laravel.lndo.site
